version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "direct"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "direct"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
